// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-servicios.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "No autenticado. Inicia sesi\xF3n para usar esta herramienta." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-servicios.ts
var list_servicios_default = defineTool({
  name: "list_servicios",
  title: "Listar servicios",
  description: "Lista los servicios (puestos) visibles para el usuario autenticado.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(50).describe("M\xE1ximo de servicios a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("servicios").select("id, nombre, cliente, direccion, tipo_turno, rondin_intervalo_minutos").order("nombre").limit(limit ?? 50);
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-asistencias.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_asistencias_default = defineTool2({
  name: "list_asistencias",
  title: "Listar asistencias",
  description: "Lista los registros de asistencia (turnos) en un rango de fechas.",
  inputSchema: {
    desde: z2.string().describe("Fecha inicial ISO, ej. 2026-08-01."),
    hasta: z2.string().optional().describe("Fecha final ISO (opcional)."),
    servicio_id: z2.string().uuid().optional().describe("Filtrar por servicio."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ desde, hasta, servicio_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("asistencias").select("id, guardia_id, servicio_id, inicio, fin, fin_esperado, horas_extra, status, tipo_turno").gte("inicio", desde).order("inicio", { ascending: false }).limit(limit ?? 50);
    if (hasta) q = q.lte("inicio", hasta);
    if (servicio_id) q = q.eq("servicio_id", servicio_id);
    const { data, error } = await q;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-alertas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_alertas_default = defineTool3({
  name: "list_alertas",
  title: "Listar alertas",
  description: "Lista las notificaciones/alertas operativas m\xE1s recientes (emergencias, rondines, turnos, visitas).",
  inputSchema: {
    solo_no_leidas: z3.boolean().default(false).describe("Devolver \xFAnicamente alertas sin leer."),
    tipo: z3.string().optional().describe("Filtrar por tipo de alerta, ej. emergencia."),
    limit: z3.number().int().min(1).max(200).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ solo_no_leidas, tipo, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("notificaciones").select("id, tipo, mensaje, leida, guardia_id, supervisor_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 30);
    if (solo_no_leidas) q = q.eq("leida", false);
    if (tipo) q = q.eq("tipo", tipo);
    const { data, error } = await q;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-visitas.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_visitas_default = defineTool4({
  name: "list_visitas",
  title: "Listar visitas",
  description: "Lista el control de visitas (entradas y salidas) registradas.",
  inputSchema: {
    desde: z4.string().optional().describe("Fecha inicial ISO (opcional)."),
    servicio_id: z4.string().uuid().optional(),
    solo_dentro: z4.boolean().default(false).describe("Solo visitantes que a\xFAn no registran salida."),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ desde, servicio_id, solo_dentro, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("visitas").select("id, nombre_visitante, persona_a_visitar, area_destino, motivo, hora_entrada, hora_salida, status, servicio_id").order("hora_entrada", { ascending: false }).limit(limit ?? 50);
    if (desde) q = q.gte("hora_entrada", desde);
    if (servicio_id) q = q.eq("servicio_id", servicio_id);
    if (solo_dentro) q = q.is("hora_salida", null);
    const { data, error } = await q;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-reportes-turno.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_reportes_turno_default = defineTool5({
  name: "list_reportes_turno",
  title: "Listar reportes de turno",
  description: "Lista los reportes de turno con su estado de revisi\xF3n del supervisor.",
  inputSchema: {
    status: z5.enum(["pendiente", "aprobado", "rechazado"]).optional().describe("Filtrar por estado de revisi\xF3n."),
    limit: z5.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("reportes_turno").select("id, guardia_id, actividades, incidencias, observaciones, status, retroalimentacion, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/crear-pendiente-puesto.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var crear_pendiente_puesto_default = defineTool6({
  name: "crear_pendiente_puesto",
  title: "Crear pendiente de puesto",
  description: "Crea una tarea pendiente para el guardia de un servicio (ej. revisar puerta 5 cada hora).",
  inputSchema: {
    servicio_id: z6.string().uuid().describe("Servicio al que aplica la tarea."),
    titulo: z6.string().trim().min(1),
    descripcion: z6.string().trim().min(1),
    frecuencia: z6.enum(["unica", "por_turno", "por_horas"]).default("por_turno"),
    horas_intervalo: z6.number().int().min(1).max(24).optional().describe("Requerido si la frecuencia es por_horas."),
    prioridad: z6.enum(["baja", "media", "alta"]).default("media")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("pendientes_puesto").insert({
      servicio_id: input.servicio_id,
      titulo: input.titulo,
      descripcion: input.descripcion,
      frecuencia: input.frecuencia ?? "por_turno",
      horas_intervalo: input.horas_intervalo ?? null,
      prioridad: input.prioridad ?? "media",
      created_by: ctx.getUserId()
    }).select().single();
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "gjhfxdlzpvakxfkkrsjd";
var mcp_default = defineMcp({
  name: "guardian-connect",
  title: "Guardian Connect",
  version: "0.1.0",
  instructions: "Herramientas de Defender Seguridad Privada. Consulta servicios, asistencias/turnos, alertas operativas, visitas y reportes de turno del usuario autenticado, y crea pendientes de puesto. Todas respetan los permisos (RLS) del usuario conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_servicios_default,
    list_asistencias_default,
    list_alertas_default,
    list_visitas_default,
    list_reportes_turno_default,
    crear_pendiente_puesto_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
